export const artists = [
  {
    id: "ernar",
    name: "Ернар Амандық",
    appleId: 1553732896,
    aliases: ["Ernar Amandyq", "Ернар Амандык"],
    styles: ["lyrical", "acoustic"],
    color: "#c69886",
    featured: true,
    description: "Жүрекке жақын әндер мен сырлы әуендер.",
  },
  {
    id: "moldanazar",
    name: "Moldanazar",
    appleId: 885269979,
    aliases: ["Молданазар"],
    styles: ["indie", "electronic"],
    color: "#9b96c5",
    featured: true,
    description: "Инди толқыны, еркін ырғақ және таныс сезім.",
  },
  {
    id: "sadraddin",
    name: "Sadraddin",
    appleId: 1522808556,
    aliases: ["Садраддин", "Садрадин"],
    styles: ["pop", "lyrical"],
    color: "#afbe9b",
    featured: true,
    description: "Жаңа қазақ поп музыкасының әуені.",
  },
  {
    id: "miras",
    name: "Мирас Жүгінісов",
    appleId: 1486813384,
    aliases: [
      "Жугунусов Мирас",
      "Мирас Жугунусов",
      "Мирас Жугінісов",
      "Miras Zhugunussov",
    ],
    styles: ["lyrical", "pop"],
    color: "#a889b4",
    featured: true,
    description: "Сағыныш пен махаббатқа арналған әуендер.",
  },
  {
    id: "turar",
    name: "Тұрар",
    appleId: 1508090539,
    aliases: ["Turar", "2RAR", "Турар"],
    styles: ["pop", "lyrical"],
    color: "#739ea7",
    featured: true,
    description: "Таныс әуендер, жұмсақ ырғақ, жаңа көңіл күй.",
  },
  {
    id: "duman",
    name: "Думан Марат",
    appleId: 1536425190,
    aliases: ["Duman", "Думан"],
    styles: ["lyrical", "pop"],
    color: "#a99181",
    featured: true,
    description: "Сезімге толы әндер мен заманауи поп әуендер.",
  },
  {
    id: "darkhan",
    name: "Darkhan Juzz",
    appleId: 1461185962,
    aliases: ["Дархан Жүз"],
    styles: ["indie", "acoustic"],
    color: "#97a78c",
    description: "Инди жинақтарын толықтыратын еркін әуендер.",
  },
  {
    id: "ayau",
    name: "Ayau",
    appleId: 1640233187,
    aliases: ["Аяу"],
    styles: ["rnb", "pop"],
    color: "#b597bb",
    description: "Жұмсақ дауыс, R&B және жаңа толқын.",
  },
  {
    id: "dequine",
    name: "Dequine",
    appleId: 1367489232,
    aliases: ["Деквин"],
    styles: ["rnb", "electronic"],
    color: "#c48b9b",
    description: "R&B жинағына арналған заманауи әуендер.",
  },
  {
    id: "kalifarniya",
    name: "Kalifarniya",
    appleId: 1503068955,
    aliases: ["Калифарния"],
    styles: ["dance", "pop"],
    color: "#b7af7d",
    description: "Жол үстіне және жақсы көңіл күйге арналған ырғақ.",
  },
  {
    id: "kazybek",
    name: "Қазыбек Құрайыш",
    appleId: 1566702041,
    aliases: ["Kazybek Kuraiysh", "Казыбек Курайыш"],
    styles: ["lyrical", "acoustic"],
    color: "#b39179",
    description: "Лирика жинағына сай жылы әуендер.",
  },
  {
    id: "bakr",
    name: "Bakr",
    appleId: 1552904011,
    aliases: ["Бакр"],
    styles: ["rnb", "lyrical"],
    color: "#9b9dba",
    description: "Жұмсақ ырғақ пен сезімге толы әуендер.",
  },
];
